server:
  port: 8020
spring:
  application:
    name: eureka-client-consumer-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true